### PR TITLE
[MSSQL] Fix serialization to parse time object

### PR DESCRIPTION
**Pull request by parthpuri-elastic**
## Closes https://github.com/elastic/connectors-py/issues/2687

We have checked all datatypes mentioned in the issue and its working as expected. For time data type we have updated the `_serialize` method.

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

#### Changes Requiring Extra Attention

- [ ] Security-related changes (encryption, TLS, SSRF, etc)
- [ ] New external service dependencies added.

## Release Note
time data type is now supported in MSSQL connector.

### CODE REVIEW

**Comment by parthpuri-elastic** [comment]
buildkite test this

**Comment by artem-shelkovnikov** [comment]
Can you update the fixture to actually use all data types from the list [here](https://learn.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql?view=sql-server-ver16) to verify that we support all of them?

**Comment by parthpuri-elastic** [comment]
> Can you update the fixture to actually use all data types from the list [here](https://learn.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql?view=sql-server-ver16) to verify that we support all of them?

Sure, will do

**Comment by navarone-feekery** [comment]
@moxarth-elastic just checking on this PR as it's grown stale; is it still on your radar to update the fixture to use the data types?

**Comment by navarone-feekery** [comment]
Sorry, meant to tag @parthpuri-elastic 🤦🏻

**Comment by moxarth-elastic** [comment]
@navarone-feekery yes, we are looking into it and update the PR soon.

**Comment by parthpuri-elastic** [comment]
buildkite test this

**Comment by parthpuri-elastic** [comment]
buildkite test this

**Comment by parthpuri-elastic** [comment]
> Can you update the fixture to actually use all data types from the list [here](https://learn.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql?view=sql-server-ver16) to verify that we support all of them?

We have not added the following datatypes because they were not supported by our Docker image.

`Cursor`, `Varbinary`, `Geomatry`, `Table`, `HIERARCHYID`

**Comment by artem-shelkovnikov** [comment]
@parthpuri-elastic I see, it's not possible to turn these on as well, right?

**Comment by parthpuri-elastic** [comment]
> @parthpuri-elastic I see, it's not possible to turn these on as well, right?

Geometry and hierarchyid are requiring to turn on CLR. Table and Cursor are simply not possible to use as a regular column in table. In order to add Geometry and HierarchyID, we need to turn on CLR but it's not possible to enable it as well for our docker image.

**Comment by parthpuri-elastic** [comment]
buildkite test this

**Review by artem-shelkovnikov — APPROVED** [review]

**Comment by praveen-elastic** [comment]
Buildkite test this

**Comment by leemthompo** [comment]
@parthpuri-elastic @artem-shelkovnikov what should the release notes mention for this one and which version?

**Pull request merged**
