### PR TITLE
[Confluence] Fix HTML Tags from Body Content

### PR DESCRIPTION
**Pull request by parth-elastic**
## Closes https://github.com/elastic/connectors-py/issues/2705

This PR fixes the issue in the Confluence connector where the body content includes HTML tags.

## Related PR https://github.com/elastic/connectors/pull/2668

Fixes Access Control Sync, `getting TypeError: 'async for' requires an object with __aiter__ method, got coroutine in connectors/sources/atlassian.py", line 122, in fetch_all_users async for users in self.client.api_call(url=url_)`

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

#### Changes Requiring Extra Attention

- [ ] Security-related changes (encryption, TLS, SSRF, etc)
- [ ] New external service dependencies added.

### CODE REVIEW

**Review by artem-shelkovnikov — COMMENTED** [review]
How does it fix the HTML tags?

**Comment by parth-elastic** [comment]
To fix the HTML tags in the "body" field, the html_to_text() (utils.py:806-814:84) function is likely being used. It removes the HTML tags and returns the content in a plain text format.

**Comment by artem-shelkovnikov** [comment]
> To fix the HTML tags in the "body" field, the html_to_text() (utils.py:806-814:84) function is likely being used. It removes the HTML tags and returns the content in a plain text format.

Likely? 

Can you also add tests and update functional tests to have this use-case - having _some_ documents (pages) have HTML while others not and verify that content is correctly loaded?

**Review by artem-shelkovnikov — APPROVED** [review]
Great job!

**Pull request merged**
