### PR TITLE
[Network Drive] fix duplicate ids in access control sync

### PR DESCRIPTION
**Pull request by moxarth-elastic**
## Closes https://github.com/elastic/connectors/issues/2821

Network Drive connector is currently indexing the access control docs (user docs) with group ids and causes duplicate ids for documents within that group. So, this PR now assigning the user id instead of group id.

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

## Release Note

Fixing the overwriting issue for access control docs.

### CODE REVIEW

**Review by seanstory — CHANGES_REQUESTED** [review]
I don't think this is changing anything, is it? I don't see any logical change, just some syntax changes.

Also, there's no test change. Please make sure that any fix is illustrated with a test.

**Comment by seanstory** [comment]
Ah! Thanks, didn't see that `rid` was defined already a few lines above the diff. Thanks for clarifying. 👍

**Review by seanstory — APPROVED** [review]
Test looks good. Thanks for the quick fix!

**Comment by seanstory** [comment]
@moxarth-elastic can you please manually backport to the 8.15 branch?

**Comment by moxarth-elastic** [comment]
> @moxarth-elastic can you please manually backport to the 8.15 branch?

@seanstory here is the backport PR: https://github.com/elastic/connectors/pull/2848, please take a look.

**Pull request merged**
