### PR TITLE
Sharepoint Server NTLM authentication support

### PR DESCRIPTION
**Pull request by moxarth-elastic**
## Related PR https://github.com/elastic/connectors/pull/2341

The existing connector only supports host header site collections and only the "sites" managed path, meaning site collections that derive their URL from the web application's URL. SharePoint supports host named site collections which can have any URL, so it doesn't make sense to force the user to only index a particular subset of sites. 
For NTLM, since aiohttp doesn't support NTLM authentication the only option with async support is "httpx", so this is what I used.

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

#### Changes Requiring Extra Attention

- [ ] Security-related changes (encryption, TLS, SSRF, etc)
- [x] New external service dependencies added.

### CODE REVIEW

**Comment by artem-shelkovnikov** [comment]
@moxarth-elastic can you also add a PR to Kibana in the meantime?

**Comment by moxarth-elastic** [comment]
> @moxarth-elastic can you also add a PR to Kibana in the meantime?

Sure @artem-shelkovnikov , let me do it

**Comment by artem-shelkovnikov** [comment]
@moxarth-elastic.

Now Sharepoint Server should be native, can you add a PR to Kibana to add the new fields now?

**Comment by artem-shelkovnikov** [comment]
Additionally, I see that functional tests fail. Can you fix them too?

**Comment by moxarth-elastic** [comment]
> Now Sharepoint Server should be native, can you add a PR to Kibana to add the new fields now?

Sure, i'll raise a Kibana PR for the newly added configuration field.

> Additionally, I see that functional tests fail. Can you fix them too?

Yes, we're looking into it.

**Comment by moxarth-elastic** [comment]
@artem-shelkovnikov I've raised a kibana PR for new field - https://github.com/elastic/kibana/pull/189030. Can you please add these labels - [release_note:skip](https://github.com/elastic/kibana/labels/release_note%3Askip) [Team:EnterpriseSearch](https://github.com/elastic/kibana/labels/Team%3AEnterpriseSearch) in the PR?

**Comment by artem-shelkovnikov** [comment]
We've taken care of Kibana PR - let's merge them together with this one once you're ready

**Comment by moxarth-elastic** [comment]
> We've taken care of Kibana PR - let's merge them together with this one once you're ready

Thanks! We're trying to fix the ftest asap, will let you know once it's ready 👍

**Comment by moxarth-elastic** [comment]
buildkite test this

**Comment by artem-shelkovnikov** [comment]
Still breaks unfortunately:

```
[FMWK][09:23:06][WARNING] Retry count: 2 out of 3. Exception: Error accessing http://127.0.0.1:8491/sites/collection1/_api/web: NOT FOUND
```

**Comment by moxarth-elastic** [comment]
Buildkite test this

**Comment by moxarth-elastic** [comment]
> We've taken care of Kibana PR - let's merge them together with this one once you're ready

@artem-shelkovnikov the functional test is fixed now, re-running the CI.

**Comment by moxarth-elastic** [comment]
Buildkite test this

**Comment by moxarth-elastic** [comment]
buildkite test this

**Review by artem-shelkovnikov — APPROVED** [review]

**Pull request merged**
