### PR TITLE
Fixing connection issue when JIRA has a path in URL (like jira.company.com/jira)

### PR DESCRIPTION
**Pull request by Gleb-Gadyatskiy**
parse.urljoin treats the first argument as host name only. Which won't work when it is host name + path (when JIRA is installed not as Root Web App). For example - https://jira.company.com/jira. The old code ignore path '/jira' and, as a result , fails to connect to JIRA on https://jira.company.com 

The proposed change free from this defect and allows to communicate with JIRA in both cases.

### CODE REVIEW

**Comment by moxarth-elastic** [comment]
buildkite test this

**Comment by moxarth-elastic** [comment]
@Gleb-Gadyatskiy You need to update the same at the following locations o/w the connector will produce the same error there
https://github.com/elastic/connectors/blob/838ce4b9c20b02a5e6fcca0f544d834727ce4553/connectors/sources/jira.py#L253-L259
https://github.com/elastic/connectors/blob/838ce4b9c20b02a5e6fcca0f544d834727ce4553/connectors/sources/jira.py#L648

**Comment by artem-shelkovnikov** [comment]
Thanks for your contribution, @Gleb-Gadyatskiy!

After your fix is ready you can run `make autoformat` to fix linting errors automatically - now you can see CI reports failure at linting stage

**Comment by seanstory** [comment]
related to https://github.com/elastic/connectors/issues/2343

**Comment by Gleb-Gadyatskiy** [comment]
Changes applied. 
Thank you

**Comment by seanstory** [comment]
@Gleb-Gadyatskiy https://github.com/elastic/connectors/pull/2377 has just merged, which I believe addresses your issue. Can you try latest, and see if it's sufficient, or if we need additional changes on top of those?

**Comment by Gleb-Gadyatskiy** [comment]
Confirmed - works fine

**Pull request closed without merging**
