### PR TITLE
[CLI] Index list - show all indices

### PR DESCRIPTION
**Pull request by vidok**
## Closes https://github.com/elastic/enterprise-search-team/issues/7060

Customers can create indices without `search-*` prefix. This PR addresses this for the `index list` command. The command displays all indices now. 

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

## Release Note

`./bin/connectors index list` shows all all open indices.

### CODE REVIEW

**Review by wangch079 — COMMENTED** [review]
>`./bin/connectors index list` shows all all open indices.

This sounds a bit strange to me. Shouldn't we limit the scope of connectors CLI within connectors?

**Comment by vidok** [comment]
> > `./bin/connectors index list` shows all all open indices.
> 
> This sounds a bit strange to me. Shouldn't we limit the scope of connectors CLI within connectors?

I was thinking about it. Currently, you can attach and detach indices from connectors so I thought it might be useful to have access to all ES indices. Also, `./bin/connectors index` namespaces is at the same lavel as `./bin/connectors connector`. Please let me know your thoughts.

**Comment by vidok** [comment]
> > > `./bin/connectors index list` shows all all open indices.
> > 
> > 
> > This sounds a bit strange to me. Shouldn't we limit the scope of connectors CLI within connectors?
> 
> I was thinking about it. Currently, you can attach and detach indices from connectors so I thought it might be useful to have access to all ES indices. Also, `./bin/connectors index` namespaces is at the same lavel as `./bin/connectors connector`. Please let me know your thoughts.

I checked the [Kibana Content -> Indices page](http://localhost:5601/app/enterprise_search/content/search_indices) and it shows all the indices. We need to add more filters but I can do it in a different PR. I think we are good.

**Comment by wangch079** [comment]
> Also, `./bin/connectors index` namespaces is at the same lavel as `./bin/connectors connector`.

Understand, but the command name is still called `connectors`

>I checked the [Kibana Content -> Indices page](http://localhost:5601/app/enterprise_search/content/search_indices) and it shows all the indices.

This makes perfect sense. Let's keep it.

**Review by wangch079 — APPROVED** [review]

**Pull request merged**
