### PR TITLE
added new object types to query from salesforce

### PR DESCRIPTION
**Pull request by MatheusGelinskiPires**
#### Pre-Review Checklist
- [ ] this PR has a meaningful title
- [ ] this PR links to all relevant github issues that it fixes or partially addresses
- [ ] if there is no GH issue, please create it. Each PR should have a link to an issue
- [ ] this PR has a thorough description
- [ ] Covered the changes with automated tests
- [ ] Tested the changes locally
- [ ] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

#### Changes Requiring Extra Attention

- [ ] Security-related changes (encryption, TLS, SSRF, etc)
- [ ] New external service dependencies added.

### CODE REVIEW

**Comment by MatheusGelinskiPires** [comment]
My bad, sorry!

**Comment by MatheusGelinskiPires** [comment]
Also, please delete/remove this pull request, please!

**Comment by seanstory** [comment]
I cannot delete pull requests, but I have sent a request to Github support to delete this.

If you have security concerns, you may also need to delete the relevant commits from your fork, and/or adjust the visibility settings on your fork/branch.

As a side note, I'm very interested to know how your experience goes with modifying connectors. If you want to chat with any of our engineers, you can find us in the `#search-enterprise` channel of [our community slack server](https://join.slack.com/t/elasticstack/shared_invite/zt-2a386f3n8-fC0DfKOOnbFATOC0S7UwnA).

**Comment by seanstory** [comment]
Github support responded with:

```
To remove unwanted or sensitive data from a repository, the commit that first introduced the data needs to be completely unreferenced in branches, tags and pull requests. A single reference anywhere will prevent garbage collection from being able to purge the data completely.
```

I have no issue with leaving this PR in existence, but merely "closed", and I don't see any obvious security issues in the diff, but if you really need the PR deleted, please delete the commit from your branch/fork, let me know, and I'll reply to Github Support.

**Comment by MatheusGelinskiPires** [comment]
Hello @seanstory , 

I prefer to go ahead and delete this PR bacause there is a few custom objects created for my employer so it could be sensitive for them.

I've deleted my fork repository so I think we are good to remove this pull request.

Thanks!

**Pull request closed without merging**
