### PR TITLE
[Google Cloud Storage] Add logs

### PR DESCRIPTION
**Pull request by moxarth-elastic**
## Part Of https://github.com/elastic/connectors/issues/2299

Adding more logs in GCS connector.

Log file: https://drive.google.com/file/d/1_ERs4rUGbEA54whCP6PZQZHLTmVmtFDl/view?usp=drive_link

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

### CODE REVIEW

**Comment by artem-shelkovnikov** [comment]
From reading the logs:

1. "Successfully connected to the Google Cloud Storage" should go to DEBUG. Failure should be a warning
2. We need to have DEBUG logs that state which resource was called , e.g. "GET /users/123", can we add those?

**Comment by moxarth-elastic** [comment]
buildkite test this

**Review by Blakehale999 — APPROVED** [review]

**Review by seanstory — APPROVED** [review]
Let's go ahead and get this in. We need more, but this is at least an improvement.

**Comment by artem-shelkovnikov** [comment]
Added to my list - gonna give it a look and approve/merge if all good this week

**Review by artem-shelkovnikov — APPROVED** [review]

**Review by jedrazb — APPROVED** [review]

**Pull request merged**
