### PR TITLE
[Confluence] Update logs

### PR DESCRIPTION
**Pull request by moxarth-elastic**
## Part Of https://github.com/elastic/connectors/issues/2299

Adds a data source validation and update existing logs.

Log file: https://drive.google.com/file/d/1NmTwME31dcvFzVRMhUCrjQaWAF93CfM6/view?usp=drive_link

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)

### CODE REVIEW

**Review by jedrazb — COMMENTED** [review]
looks good, when handling client errors in `_handle_client_errors`
- can we log url that is causing `500`
- when handling other errors (else raise at the end) can we log as error full `exception` and `url`

**Comment by jedrazb** [comment]
in `api_call` the `ServerDisconnectedError` should be probably logged as well (as we are closing the session and re-raising)

**Review by artem-shelkovnikov — COMMENTED** [review]
1. "Started pagination for the API endpoint: rest/api/search?cql={query} to host: https://jira-connector.atlassian.net/wiki" should be DEBUG. Also query is not actually shown
2. Sync should report progress while in INFO. Now I see nothing - can we log what entities are fetched in INFO?
3. Paginated calls report only the first call, can you make sure every page call generates a log line?

**Comment by artem-shelkovnikov** [comment]
@moxarth-elastic can you share updated log lines in DEBUG for all the log issues when you finish addressing comments?

**Comment by moxarth-elastic** [comment]
> @moxarth-elastic can you share updated log lines in DEBUG for all the log issues when you finish addressing comments?

Here is the updated log file: https://drive.google.com/file/d/1NmTwME31dcvFzVRMhUCrjQaWAF93CfM6/view?usp=drive_link

**Comment by artem-shelkovnikov** [comment]
Looks better, a couple more:

- "Successfully connected to Confluence" should be DEBUG when called from `ping` method, it's great to have it when you call it from `get_docs` though. Failure to connect should be WARN
- "Started pagination for the API endpoint: rest/api/search?cql={query} to host: https://jira-connector.atlassian.net/wiki" - notice `{query}` is not inlined. Can we also use generic message here, like you did for `GET` call? Also this line should not be info.

**Comment by moxarth-elastic** [comment]
buildkite test this

**Review by jedrazb — DISMISSED** [review]
LGTM

**Review by jedrazb — APPROVED** [review]

**Comment by navarone-feekery** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/connectors/pull/2860)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
