### PR TITLE
Update Oracle connector to support service name

### PR DESCRIPTION
**Pull request by parth-elastic**
## Closes https://github.com/elastic/connectors/issues/2382

Added the new RCF for connecting to Oracle with Service name.

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [x] Considered corresponding documentation changes
- [x] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

### CODE REVIEW

**Review by artem-shelkovnikov — COMMENTED** [review]
Just in case, have you checked that this change is forwards-compatible? E.g. having a working connector with old configurable fields will not break the connector once this change is applied?

**Comment by parth-elastic** [comment]
Yes, verified that this change maintains forwards compatibility. The new configuration will seamlessly integrate with existing connectors, ensuring they remain operational after the update. The previous configuration, known as the SID database, will continue to function properly. However, there is an update: if the service_name is selected, the DSN will now be the service name instead of the SID.
image (5)

**Review by artem-shelkovnikov — APPROVED** [review]

**Comment by moxarth-elastic** [comment]
Buildkite test this

**Comment by leemthompo** [comment]
Docs PR: https://github.com/elastic/enterprise-search-pubs/pull/4415

**Pull request merged**
