### PR TITLE
Build and publish Wolfi-based images only

### PR DESCRIPTION
**Pull request by oli-g**
With 8.14 we published two image flavours:
* `docker.elastic.co/enterprise-search/elastic-connectors` (based on Debian)
* `docker.elastic.co/enterprise-search/elastic-connectors-wolfi` (based on Wolfi)

Only `docker.elastic.co/enterprise-search/elastic-connectors` (based on Wolfi) will be published from 8.15.

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [ ] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [ ] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [x] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

### CODE REVIEW

**Review by acrewdson — APPROVED** [review]

**Review by seanstory — COMMENTED** [review]
Shouldn't this remove the current `Dockerfile` and rename `Dockerfile.wolfi` -> `Dockerfile`? Same for the ftest dockerfiles?

**Comment by oli-g** [comment]
@seanstory We can't remove `Dockerfile` because we want our users to build their own custom connectors (see [docs](https://github.com/elastic/connectors/blob/6b27410/docs/DOCKER.md#4-update-the-configuration-file-for-your-self-managed-connector)): [docker.elastic.co/wolfi/python](https://github.com/elastic/connectors/blob/6b27410/Dockerfile.wolfi#L1) is not a public image, so `docker build` would fail for users.

**Comment by seanstory** [comment]
Can we not make `docker.elastic.co/wolfi/python`  a public image? I don't love the idea of us shipping one image, but instructing customers to build something else that's less secure.

**Comment by oli-g** [comment]
> Can we not make `docker.elastic.co/wolfi/python` a public image?

No, we can't at the moment. For the same reason `cgr.dev/chainguard/python:3.10` is not made public by Chainguard (see _[Contact us](https://www.chainguard.dev/contact) for access to this image_ [here](https://images.chainguard.dev/directory/image/python/versions)). Only `latest` and `latest-dev` tags are public, but they come with the latest 3.12 Python version.

**Pull request merged**
