### PR TITLE
[Network Drive] Change traversal strategy to ingest as you go instead of pre-fetching the whole tree

### PR DESCRIPTION
**Pull request by akanshi-elastic**
## Closes https://github.com/elastic/connectors/issues/2265###
This PR contains the traversal of directories/subdirectory changes, now we are using scandir method to fetch data from network drive, which start ingestion data in seconds after connector starts syncing.

#### Pre-Review Checklist
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

#### Changes Requiring Extra Attention

- [ ] Security-related changes (encryption, TLS, SSRF, etc)
- [ ] New external service dependencies added.

### CODE REVIEW

**Comment by artem-shelkovnikov** [comment]
Can you test it against a reasonably large network drive (large enough so that without this change, walking through it would take at least 5 minutes) and provide benchmarks for the test?

Some numbers that are interesting to me:
- Time to sync all the data
- Time until first document lands into the index
- Perf8 reports before/after

**Comment by praveen-elastic** [comment]
> Can you test it against a reasonably large network drive (large enough so that without this change, walking through it would take at least 5 minutes) and provide benchmarks for the test?
> 
> Some numbers that are interesting to me:
> 
> * Time to sync all the data
> * Time until first document lands into the index
> * Perf8 reports before/after

Hi [@artem-shelkovnikov](https://github.com/artem-shelkovnikov) Please find the response as below:
Time taken to sync all the data - 1 hour 47 mins to Index 152416 docs
Time until first document lands into the index - 1 sec
Link to Perf8 reports:- https://drive.google.com/drive/folders/1xtT4TibPH-Y0rHegUBwD9rkAtlW6KsQD?usp=drive_link

**Comment by artem-shelkovnikov** [comment]
RSS graph looks concerning - it seems to never recycle the memory, can you check if you're releasing memory during traversal?

See graph before the change - you can see that RSS decreases from time to tim: 

image

**Comment by praveen-elastic** [comment]
> RSS graph looks concerning - it seems to never recycle the memory, can you check if you're releasing memory during traversal?
> 
> See graph before the change - you can see that RSS decreases from time to time:

You are right, this does seem concerning, I have found a resolution, currently testing that, will update that once done.

**Comment by praveen-elastic** [comment]
I've now changed the code to use iterative approach which has improved the rss and also fixed the loop_lag issue, attaching the two zips 
[perf8-report-network_drive_recursive.zip](https://github.com/elastic/connectors/files/14773659/perf8-report-network_drive_recursive.zip)
[perf8-report-network_drive_iterative.zip](https://github.com/elastic/connectors/files/14773661/perf8-report-network_drive_iterative.zip)

**Comment by artem-shelkovnikov** [comment]
@praveen-elastic are the results received from ftest?

Where did the previous result come from, with more data? Is it possible to also check there? The charts that you've attached look okay, but I'm not sure why the results are the way they are:

- RSS is recycled in both
- Why did event loop lag decrease?
- Why did run time decrease?

**Comment by praveen-elastic** [comment]
yes, these are the stats of ftests, the previous one was with actual connector sync with a lot of data. 

I did run the connector with that data for the updated code but didn't capture perf8 report, the total time to index was reduced to around: `1h 42 mins`(earlier approach took 1 hr 47 minutes). I'll try to run the connector again with that data tomorrow to generate the perf8 stats.

By the way, I shared the ftest stats as the RSS fluctuations in new code were lot less and I thought loop lap reduction was a good thing. Also the disk usage was also reduced from 11 Gb to 3 Gb.

**Comment by artem-shelkovnikov** [comment]
It indeed looks good, but disk usage reduction looks too good to be true - is it possible we're missing some data?

Would be great to compare the data (index size + number of records) for both old/new implementation for the real data source you used before in the report

**Comment by praveen-elastic** [comment]
> It indeed looks good, but disk usage reduction looks too good to be true - is it possible we're missing some data?
> 
> Would be great to compare the data (index size + number of records) for both old/new implementation for the real data source you used before in the report

Hi @artem-shelkovnikov here are the perf8 stats for connector sync with the updated code and the same data 
[perf8.zip](https://github.com/elastic/connectors/files/14788224/perf8.zip), rss seems to be recycled in this one.

**Comment by artem-shelkovnikov** [comment]
Still seems to grow: 
image


Just to compare, how does this graph looks for sync to same data source, but from `main`, not from this branch?

**Comment by praveen-elastic** [comment]
Hmm, let me generate perf8 for the code on main currently.

**Comment by praveen-elastic** [comment]
@artem-shelkovnikov here's the report of code from main branch with same data 
[perf8-main-branch-code.zip](https://github.com/elastic/connectors/files/14792899/perf8-main-branch-code.zip)

**Review by artem-shelkovnikov — APPROVED** [review]
Current branch RSS looks similar, thus it should be good to merge, great job!

**Comment by sphilipse** [comment]
@artem-shelkovnikov do we want to backport this to 8.13 still?

**Comment by artem-shelkovnikov** [comment]
@sphilipse yup I'm planning to do a backport after we release 8.13.1, so hopefully tomorrow

**Pull request merged**
